### ISSUE TITLE
Bugfix release for 1.1

### ISSUE THREAD

**Issue by Digenis** [scrapy/scrapyd#146]
1.1 is supported but left with bugs for quite some time.
There are bugs already fixed in master
that could make for a bugfix release.

- [x] #144 (missing doc for argument to scheduler)
- [x] #113 (bug: setting always overridden), duplicates: #80, #67
- [x] #112 (missing doc for config)

I'm waiting for suggestions for bugfixes not merged into 1.1
or confirmed bugs that can be fixed in a backwards compatible way.

**Comment by Digenis** [comment]
closing in favour of PR #147
